[project]
name = "parlir"
version = "0.1.0"
description = "A Test Collection for Information Retrieval over Portuguese Parliamentary Initiatives"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.15.0",
    "ranx>=0.3.21",
    "rdflib>=7.6.0",
    "scikit-learn>=1.9.1",
    "transformers>=5.17.0",
]
